name: Push the latest code to AWS Elastic Beanstalk
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 🚚 Get latest code & build
        run: npm install && npm run build

      - name: Copy Procfile to the dist folder
        run:  cp Procfile ./dist

      - name: Generate deployment package
        run:  cd ./dist && zip -r ../dist.zip * .*
        
      - name: Set environment variable
        run: cd ./dist && export APP_PORT=${{ secrets.APP_PORT }}  && export JWT_EXPIRATION=${{ secrets.APP_JWT_EXP }} && export JWT_SECRET=${{ secrets.APP_JWT_SECRET }} && export BCRYPT_SALT=${{ secrets.APP_SALT }} && export DATABASE_URL=${{ secrets.APP_DB }}
        
      - name: Deploy update to server
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: ${{ secrets.AWS_APP_NAME }}
          environment_name: ${{ secrets.AWS_ENV_NAME }}
          existing_bucket_name: ${{ secrets.AWS_BUCKET_NAME }}
          region: eu-west-2
          version_label: ${{ github.sha }}
          deployment_package: dist.zip


          


          

          
